### ISSUE TITLE
Needed for FPP calculations

### ISSUE THREAD

**Issue by timothydmorton** [benmontet/k2-characterization#1]
I'll need the following for each candidate.  Some of these are in the Paper 1 table, but others aren't. @dfm, ideally the photometry would be able to be machine-grabable (via either ketu or kplr?) so that I can build the K2 submodule of my FPP code to be as generally useful as possible (i.e. be able to give an EPIC ID, period, and epoch, and get the requisite phase-folded/detrended photometry).  In the meantime, old-fashioned files/tables are OK, too, since there's only a few dozen we're working with right now.
- Phase-folded, de-trended transit photometry for each candidate.
- ra, dec 
- orbital period 
- All available apparent magnitudes
- All available spectroscopic properties (Teffs, loggs, fehs)
- Maximum possible depth of secondary in each light-curve---I don't think this was in Paper 1, but should be here.  
- measured rp/rs
- any available AO contrast curves

**Comment by benmontet** [comment]
Phase-folded, de-trended transit photometry for each candidate.  -> Dan will supply this

ra, dec   -> This is in a table in Paper I

orbital period -> This is in a table in Paper I

All available apparent magnitudes  -> See table in this repository.

All available spectroscopic properties (Teffs, loggs, fehs) -> How do you feel about photometric and model-dependent? It is my intention to have these locked down by the end of the day. The only one we have spectroscopy for is the nearby M, and you should have that already.

Maximum possible depth of secondary in each light-curve---I don't think this was in Paper 1, but should be here. -> We threw out anything with a visible secondary, so this should be at the level of the noise. Dan, are you on this one?

measured rp/rs -> This is in the Paper I table.

any available AO contrast curves -> We have AO for 7 systems. 
201912552
201828749 -> few " binary
201577035
201613023
201546283 -> 2" companion
201295312
201403446

Brendan Bowler is doing the contrast curves; I will ping him again.

**Comment by timothydmorton** [comment]
Yeah, I don't need spectra; just helps if we do have it.  Photometric estimates of stellar props are fine.

**Comment by benmontet** [comment]
Okay, model-dependent (Dartmouth and Padova) parameters that I believe represent the statistical uncertainties from the photometry can be found on the main page of the repository ("dartmouth_params.txt" and "padova_params.txt"). The Fe/Hs are really unconstrained, as you might expect (the models are only coarsely sampled, and there's not a huge effect) but the other observables look reasonable to me, and they're more or less consistent with each other.

Next step is to combine them in some self-consistent way, but this should be close to the final product.

**Comment by dfm** [comment]
Hi team. Sorry for being so quiet. I'm back ready to help now.

@timothydmorton: a few questions.
1. For the light curve, I can give you a "de-trended" light curve but it might be better if I just give you the statistics that you need. For example, I can fit your trapezoid model to the data using the likelihood function that I used to fit transit model in Paper 1. This would be best because any light curve that I give you will be already conditioned on some fiducial transit model... y'know what I mean?
2. For the secondary depth, how do you normally compute that? Do you go to exactly phase/2 and compute the depth there? Most of the secondaries that I saw for the EBs in our sample were some what offset from phase/2.
3. For RP/R\* do you want samples or quantiles or what? I have all the things.

**Comment by timothydmorton** [comment]
1.  Fitting the trapezoid model and delivering samples would be great; I could certainly make that work.  The trapezoid model I use is the "traptransit" function [here](https://github.com/timothydmorton/VESPA/blob/master/vespa/transit_utils.pyx), which assumes "continuum" at normalized flux=1.  You can adapt that as necessary for your modeling, as long as you keep the same parameterization.
2.  For secondary depth, what I'd like is to know what's the depth of the strongest signal, at any phase (excluding phase=0), found at the same period as the candidate.  
3.  For Rp/Rs I'm OK with just point estimates, which I can pull from the Paper 1 table.

**Comment by dfm** [comment]
OK. I'm on it for the trapezoid fitting. I'll have to think a bit about the secondary thing because I don't currently save everything I need. That being said, it won't be hard to pull it out. I'll get something to you tomorrow.

**Comment by dfm** [comment]
I'm almost finished sampling but I have one question. What prior do you normally put on T/tau? Flat in log? It can blow up to infinity and still be a good fit...

**Comment by timothydmorton** [comment]
right-- sorry, forgot to mention...I use a flat prior on (2,30).

**Comment by dfm** [comment]
OK. Samples for all the candidates are in the `.h5` files in http://bbq.dfm.io/~dfm/research/bbq2/ketu/trap/

In each file, there is a `samples` dataset where the columns are `T, delta, T/tau, period, t0`. For the multis, I sampled it all together so there will be 10 columns instead of 5.

I'll get on the maximum secondary depth thing.

**Comment by dfm** [comment]
OK. Here are the estimates of the deepest secondary at the same period as the primary: http://bbq.dfm.io/~dfm/research/bbq2/ketu/secondary.csv

The columns are:
1. EPIC ID
2. Period in days
3. Depth of the primary (as estimated by the pipeline) in ppt
4. t0 for the primary in annoying units used internally by the pipeline... don't ask
5. Depth of the "secondary" in ppt... this is the most significant signal at the period of the primary after masking the transits of the primary
6. t0 for this secondary peak in the same units as 4

Let me know if you need anything else.

**Comment by timothydmorton** [comment]
Alright, looks great-- thanks!  Probably tomorrow I'll turn to amending my FPP code to take externally generated trapezoid posteriors, and then I'll be able to include these limits.  Look forward to FPP calculations by the weekend!

**Comment by benmontet** [comment]
This sounds excellent!

Do you also have a time estimate for your stellar properties? I'd prefer to
use yours because I really like the way you're handling extinction. If
there's anything I can do to help you get the WISE model data incorporated,
let me know!

**Comment by benmontet** [comment]
I don't have the contrast curves from Brendan yet, but we have SDSS imaging for this field.

Four targets have companions within delta r of 8 mags and 12 arcseconds. These are 201295312, 201465501, 201546283, and 201779067. Of these, the second and fourth are too faint to cause the observed transit depth (although #4 is almost certainly an EB anyway). 1 and 3 could cause the transits, but I would guess that you'll show the transit shape is wrong for an EB regardless of the existence of a companion, especially for 201295312. (The photometry for these stars is included in the photometry table in the repository).

SDSS claims 95% completeness to r=22.2 and a 1.4 arcsecond PSF, so you could use this to create a pseudo-contrast curve over the range ~3-12".

For ones we do have AO data for and have high proper motions, I'm going to use the old POSS data to show there's nothing directly behind the star currently, so the contrast curve will go to 0" separation. I'm definitely going to do this for the M dwarf; let me know if there are any others where you would find this helpful.

**Comment by timothydmorton** [comment]
Are the Kepler mags of these stars in a table somewhere?

**Comment by benmontet** [comment]
They're in the EPIC but that's it. And those are given just based on
however the proposer wanted to estimate Kp, so they're inconsistent from
proposal to proposal.

If you want something systematic, I think the best thing may be to derive
it yourself based on the other colors, like the Kepler team's
recommendation:
1. if   ( _g_ − _r_ )   ≤   0.8    then    Kp   =   0.2 _g_   +   0.8 _r_
2. if   ( _g_ − _r_ )   >   0.8     then    Kp   =   0.1 _g_   +   0.9
   _r_

And then Kp \approx r for the M dwarfs.

**Comment by timothydmorton** [comment]
FPP calculations finished.

**Comment by benmontet** [comment]
Does the existence of the companion found in AO change anything for EPIC 201828749?

**Comment by timothydmorton** [comment]
I'm not yet set up to calculate this, so I think I'll just talk
around/about it rather than be quantitative for now.

On Wed, Mar 11, 2015 at 4:52 PM, benmontet notifications@github.com wrote:

> Does the existence of the companion found in AO change anything for EPIC
> 201828749?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/benmontet/k2-characterization/issues/1#issuecomment-78368872
> .

## 

about.me/tim.morton
