### ISSUE TITLE
Tasking people with specific tasks before sending to coauthors

### ISSUE THREAD

**Issue by benmontet** [benmontet/k2-characterization#14]
Specific things we need:
- [x] Table on stellar properties (with inflated errors): @benmontet
- [x] Table on nearby background targets: @benmontet
- [x] Color-color plot with targets (likely r-J/J-K): @benmontet
- [x] Finishing up discussion: @benmontet
- [x] Appendix: @dfm 
- [x] Table of planet properties (using inflated stellar errors): @dfm 
- [x] Planet properties for EPIC 201912552 using the spectroscopic stellar params: @dfm 
- [x] Figure showing phase-folded transit events, with appropriate caption that these represent the result with some fiducial model, and should not be used directly for science: @dfm, or @dfm puts phase-folded data somewhere and @benmontet makes the plot
- [x] Comments about the system with the AO imaging that shows a binary, but we still call it a planet because from looking at the transit it's obviously planet-shaped: @timothydmorton. I currently put this in section 4.1, but you can place it anywhere you think is appropriate.
- [x] Reading through it once: @benmontet AND @dfm AND @timothydmorton.
- [x] AO section: Brendan.

It's my intention to send it off to all coauthors at the end of the day Thursday. We don't have to have all of these things checked off by then, but the more the better. I think having all of mine done by that point is doable, and if we can at minimum have the planet properties table and the text for that section done too, that would be ideal.

**Comment by timothydmorton** [comment]
I've been focusing on code documentation today (`isochrones` docs are live at http://isochrones.readthedocs.org now!), so I haven't had a chance to contribute much to the text yet, though I do expect to make some significant editorial contribution once I get around to it, but this may not be until the weekend.   

And for the `vespa` code, I have a decent bit of refactoring and documentation to do before going live with that, though my goal is to have this done by the time we submit.

@dfm, I'd also like to re-run the star properties once more one of these days, because I've made some minor changes to the code.  I don't expect this to change anything drastically, but presumably your planet properties can be updated relatively easily if I do that?

**Comment by benmontet** [comment]
Hey @dfm how is that appendix and/or figure going?

**Comment by dfm** [comment]
Oops. Still sucking over here. I'll dedicate tomorrow morning to do that. Sorry about the delay!

**Comment by benmontet** [comment]
Hey @dfm how is that appendix and/or figure going?

The table really must be done today to send out to coauthors again. I know you are set up to do it since you did one version already.

**Comment by dfm** [comment]
I've added the updated table. As I mentioned in a previous issue, I think I'm just going to drop this method of doing things because I just don't have enough MCMC samples to do what I want to do!

I'll run chains for each of the targets using the measured stellar parameters tonight and update the table. I've just cut the appendix cause it won't be necessary anymore.

**Comment by timothydmorton** [comment]
My situation is that I am still churning through `vespa` documentation, as well as a re-factoring in order to make it a single package, etc.  I also need to make the generic usage case as transparent as possible, which I have not yet done. 

So I've got a ways to go before that'll be ready, and I want it to be at least presentable before we post to arxiv.  I also want to give the paper a good read-through, which I haven't yet had the chance to do.  I'll keep you posted on my progress, but chances are I won't be able to make my text contributions before you'd send it out to co-authors again, Ben, if you want to do that today.

**Comment by benmontet** [comment]
@dfm: This sounds great to me. Verifying two things:

1) Does this account for dilution in the one known binary?
2) You are using the spectroscopic parameters for 201912552, and not the photometric onces?

@timothydmorton This also sounds excellent. If we submit to arXiv on Friday at 4pm, it will appear in the 8pm EDT Monday mailing. Does that give you enough time? I think the only other thing I need from you that will go into the paper is discussion of that one system where we know its a binary, but vespa calls it a definitive planet.

**Comment by benmontet** [comment]
Pinging you both again on the above questions.

@dfm What do you want to do with this figure? If you put somewhere the light curves with the maximum likelihood systematics model removed (or just put the light curves and the maxL systematics models in the same places) I'll phase-fold and plot.

**Comment by dfm** [comment]
I haven't dealt with the dilution yet. I'll get on it.

The updated code is almost finished and surprisingly it didn't change the numbers much at all. I was a bit worried that I didn't have enough samples but it looks good!

The corrected light curves based on the median of posterior parameters have been uploaded here: http://bbq.dfm.io/~dfm/research/bbq2/k2-characterization/corr/ I'm still running on 201929294 but it'll be up soon. To open the HDF5 files, you can use something like:

```
import h5py
with h5py.File("SOME_EPIC/1.h5", "r") as f:
    period = f.attrs["period"]
    t0 = f.attrs["t0"]
    corr_data = f["corr_data"][...]
    model = f["model"]

time = corr_data["time"]
corr_flux = corr_data["corr_flux"]

time_since_transit = model["time_since_transit"]
model_flux = model["model_flux"]
```

Let me know if you have any issues.

The .png files should give an idea for what each plot will look like.

**Comment by benmontet** [comment]
Are the models not corrected for integration time? Some of them don't quite
line up with the flux, and they have very sharp edges, so I think that's
correct but want to make sure.

**Comment by dfm** [comment]
The models are corrected for integration time! What do you mean by "not
lined up"?

**Comment by benmontet** [comment]
I just clicked through them all and apparently I just got unlucky in
spotchecking a few, so I mostly retract my previous statement.

Except for two:
1) what's going on with 201257461? The depth is way off.
2) The depth is also strange with 201779067, but I presume that's the
effect of fitting a boxcar in the systematics model, while now fitting a
proper transit model?

**Comment by dfm** [comment]
I'm not at my computer right now so I can't confirm this but my guess with
these two is probably that the median of posterior parameters are a bad
fit. Maybe it would be better if we plot a set of samples. I'll switch that
up tonight

**Comment by benmontet** [comment]
Okay.

201754305 is also missing, as is 201505350 (which has two planets)

**Comment by dfm** [comment]
True. The code is still running for those ones. I hadn't realized. I'll update as soon as it finishes

**Comment by timothydmorton** [comment]
@dfm, do you have somewhere in some easy-to-pull-out way the size in pixels of the apertures you used for the photometry for each star?  I'd like to be more quantitative/precise about the "allowed sky area" for the false positive probabilities, and that would help.

**Comment by dfm** [comment]
All of the corrected light curves are in place. The two that are screwed up (201257461 and 201779067) are wrong because I limited b < 1.02 and these ones actually want it to be larger... so they're actually just bad fits :-\

**Comment by benmontet** [comment]
I don't get what's going on with the "model_flux_nn" entries in the hdf5
files now. It looks like they're just lines of y=x? How do I access the
actual models?

**Comment by timothydmorton** [comment]
I'm about to set up the final (?) FPP runs, and need to know the following:
- @benmontet, which generation of stellar fits did we decide to put in the table?  BVgriJHK+WISE?  Leaving out gri?
- Pixel areas of all the apertures (@dfm)

**Comment by dfm** [comment]
@benmontet: I've fixed the bug so all the correct models are in place now and the planet table should have everything now. Next up: breakfast. Then words.

@timothydmorton: I actually don't have the aperture areas saved. I do have the aperture radius (in pixels) that I used for each target. I've saved that list here: https://github.com/benmontet/k2-characterization/blob/master/apertures.csv

**Comment by benmontet** [comment]
I'm using the fits with all the colors.

**Comment by timothydmorton** [comment]
@benmontet -- The SDSS search you did for close companions went out to 12" from the target source positions.  Many of the aperture radii are 4 or 5 pixels, corresponding to 16-20".  I think that our SDSS close-source selection should correspond to _at least_ the pixel aperture radius; maybe even a bit more.  I think I'm going to run my FP models considering a potential BG area of the aperture radius + 1 pixel.

**Comment by benmontet** [comment]
@dfm 201257461 looks strange in the opposite direction right now. It's the only weirdo. 
![f2](https://cloud.githubusercontent.com/assets/1314530/6783758/f5100726-d151-11e4-8e8e-8174fb22f042.png)

**Comment by dfm** [comment]
I can run it again tonight with a larger b limit if you want. But I won't
be able to set it running until around 4 though. Sorry!

**Comment by benmontet** [comment]
That's fine with me. It doesn't change any analysis, we know it's a false positive. It's just this figure and one line in a table. 

Do you put a limit on Rp/Rstar? And do you fit for dilution as well? This _has_ to be a big thing eclipsing another big thing, far in the background behind our target thing. I wonder if you can even make this eclipse shape happen with only two bodies with one of them non-luminous.

**Comment by benmontet** [comment]
@dfm Could you also either update the table or send me info (values, samples, whatever) for T0 in the planet properties? I have values but not uncertainties.

**Comment by benmontet** [comment]
@timothydmorton Table updated with potential background contaminants. I haven't updated the text yet, but I now search to 25" and record an object ONLY if it is bright enough to cause the transit event (otherwise this table would go on for days).

I also remove objects if they're obviously galaxies, of course. I don't follow the SDSS classifiers because they don't seem to be very good, so my cut is if (a) bye eye at the image, clearly a galaxy or (b) has a spectroscopic redshift.

**Comment by timothydmorton** [comment]
OK-- thanks Ben!  I'll have to digest this and make some judgments on how
to handle it.

**Comment by timothydmorton** [comment]
@benmontet, can you add to bg stars table the aperture radius that Dan used for the photometry (apertures.csv)?  I would do it, but if you're generating the table automatically, you probably should.

**Comment by benmontet** [comment]
@timothydmorton Yes, that's a great idea. They're updated in the version I just pushed.

**Comment by benmontet** [comment]
@dfm: 201257461?

**Comment by dfm** [comment]
@benmontet: Updated. Also you should remake the full light curve figure because I had a bug with the way I was making it before.
