### ISSUE TITLE
Stellar Teff vs Mass/FeH

### ISSUE THREAD

**Issue by benmontet** [benmontet/k2-characterization#15]
There are a few stars that, based on their photometry (esp r-J,J-K) I would guess are more massive than the Sun. 

![color_color](https://cloud.githubusercontent.com/assets/1314530/6622706/be143490-c8b4-11e4-9d3b-a377509a1f55.png)

Indeed, our stellar parameters table has Teff > 5760 for these, but this is converted into a mass of ~0.8 solar and a metallicity of ~-1 dex. 

What specifically is going on here? Are we sure these aren't F stars that we're messing up somehow?

The particular EPICs are 201295312, 201403446, and 201779067; there are a few others that are close to falling in this category (201613023, 201384232, 201393098)

**Comment by timothydmorton** [comment]
It's possible I ran these with a 500pc max_distance limit.  Let me check on this.

**Comment by benmontet** [comment]
Any success? It looks to me like that might be the case, especially given the posterior on 201702477

**Comment by timothydmorton** [comment]
Hey sorry- yeah, I'm sure this is at least part of what's going on; I re-ran the [posteriors](http://www.astro.princeton.edu/~tdm/k2/starmodels_inflated/); though now there appears to be a bug in the way I'm making the observed samples, which I was about to fix but have been called away for something else in the meantime... stay tuned.

**Comment by timothydmorton** [comment]
p.s. i haven't gone through these to check to make sure that older issue of thinking one of the stars was a giant (the reason i'd put the distance limit in the first place) isn't cropping up again...

**Comment by benmontet** [comment]
Sounds great. Staying tuned!

The giant thing was because we weren't fully sampling the parameter space at the beginning, and the sampler was getting caught in a local minimum, right? If so hopefully the other fixes you made along the way well keep that from coming back!

**Comment by timothydmorton** [comment]
Yeah spot-checking the Crossfield star suggests this isn't a problem anymore.

**Comment by benmontet** [comment]
Excellent! Let me know when all the new samples are run and posted (to the same place?) and I'll remake the stellar params tables.

**Comment by benmontet** [comment]
I see the starmodels_inflated files were updated yesterday, are those _the_ ones to use for the paper, or is one more run required?

**Comment by timothydmorton** [comment]
They're now updated.  I'm not fully satisfied with the results for these particular systems, though.  I'm making some new plots and then I'll post and we can explore.

**Comment by timothydmorton** [comment]
OK, so here's one of the questionable ones.  Teff of ~6300 but mass preferring <1 Msun?

![image](http://www.astro.princeton.edu/~tdm/k2/starmodels_inflated/201403446_physical.png)

Part of the clue here must be in the "observed" triangle plot below.  As you can see, r, i, W3, and W1 don't seem to match well with the chains, so there's some tension going on here.  Maybe looking at all the colors at once like this is exposing a limitation on the way we normally interpret stellar colors, or exposing more deficiencies in the models, or something like that.  I'm not sure how best to proceed with these---with this one, I'll try to see how it does with just JHK+WISE and see how that turns out, maybe? 

![image](http://www.astro.princeton.edu/~tdm/k2/starmodels_inflated/201403446_observed.png)

**Comment by benmontet** [comment]
Huh, that's strange. There is some power up where we expect it to be
(around 1.2), it's surprising to me how much that's getting swamped by the
low-metallicity tail. I think you're right that this must be telling us
something about the models (or about our priors also, I suppose).

I would be interested to see what it looks like with just JHK + WISE.

What is your prior on distance? I suppose it should be weighted towards
larger distance, since there is more space to put a star at 500 pc than at
300 pc? But that doesn't explain why these super low metallicity things are
so favored.

**Comment by timothydmorton** [comment]
JHK + WISE doesn't look much better.  Here is the situation with just r-J-K, to model what it is you're seeing.  It does seem to be a bit better, but still not too illuminating.

![index](https://cloud.githubusercontent.com/assets/1895387/6643697/c699f8c2-c984-11e4-9a83-ff56e7a56284.png)

![index](https://cloud.githubusercontent.com/assets/1895387/6643699/cfededde-c984-11e4-88e9-e24e173e6021.png)

I have currently a flat prior in distance, which is wrong, I suppose.  (though I do have a comment in my loglikelihood that says "distance prior?"...that should count for something.)  I'll try playing around with this a bit some more.  But I think there's a clue here that there's no constraint on metallicity whatsoever, indicating there's some mismatch going on.  Do you have a good suggestion as to what I could maybe use as a well-motivated metallicity prior for this part of the Galaxy?

**Comment by benmontet** [comment]
We're looking pretty much straight out of the galactic plane, so we really care about the metallicity at a column of r=8 kpc from the center of the MW. Figure 7 of http://arxiv.org/pdf/1110.5933v1.pdf says that it should be something like [Fe/H] = -0.5 \pm 0.25 beyond 500 pc, and slightly higher closer in? But that's just trying to eyeball off a plot.

I don't know of anything that gives a specific more useful equation, this is a little out of my wheelhouse. @dfm has done some SDSS stuff before---do you have a good equation/reference for the metallicity distribution at 8 kpc?

**Comment by timothydmorton** [comment]
Distance prior helps a bit, and metallicity prior helps a lot.  Having even a rough metallicity prior is important, apparently!  Here I've given -0.4 +/- 0.4 as a prior, sort of arbitrarily. (This is back to using all photometry, btw.)  Got a question in to Jo Bovy about what a good prior would be to use.

![index](https://cloud.githubusercontent.com/assets/1895387/6644266/e1130302-c988-11e4-846a-aae6041bdd2a.png)

**Comment by benmontet** [comment]
Great. Let's wait and see what Jo says, and then use that. I'll also write some words about the degeneracy between stellar mass/radius and metallicity we observe, and a couple sentences about a star less massive than the sun being hotter, if it's very metal poor (fully understandable as an opacity effect)

**Comment by timothydmorton** [comment]
Yay for Fe/H prior!  OK, I'll re-run everything with this now, and then hopefully everything will be production-ready.

![index](https://cloud.githubusercontent.com/assets/1895387/6645435/0f62dac0-c993-11e4-8fd8-e2a9315df67f.png)

**Comment by benmontet** [comment]
Excellent! Those look great. And based on that paper Jo sent those priors
are definitely believable---it looks like Fe/H is unchanged up to almost 1
kpc in their analysis.

Once those are done I'll remake the stellar params tables, and then I'll
send out to authors with the comment that some parts are still WIP but we
hope to finish them and submit very soon.

**Comment by timothydmorton** [comment]
New chains/plots are up.

**Comment by benmontet** [comment]
Great!

Does isochrones have a DOI/presence on the ASCL? If so we can cite it!

**Comment by timothydmorton** [comment]
It has a DOI (on the github page), and will have an ASCL-- though there's a
chicken-egg issue that it doesn't have a number yet because it's not in a
paper...so it can be a stub citation until we go to arxiv, maybe...

On Fri, Mar 13, 2015 at 10:13 PM, benmontet notifications@github.com
wrote:

> Great!
> 
> Does isochrones have a DOI/presence on the ASCL? If so we can cite it!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/benmontet/k2-characterization/issues/15#issuecomment-79704814
> .

## 

about.me/tim.morton
