### ISSUE TITLE
Data?

### ISSUE THREAD

**Issue by timothydmorton** [benmontet/k2-characterization#16]
Have we settled on what all the data is that we're going to put up for this project?  For me in particular, I think I'm going to want to put up a tar file of all the FPP-related data on zenodo (this will include the starmodel fits).  Probably makes sense to combine everything into one zenodo archive.

**Comment by benmontet** [comment]
I think FPP, starmodel fits, planet samples, AO data, and SpeX spectrum of 201912552? Is there anything else worth including?

**Comment by timothydmorton** [comment]
I've put a tarball of all the FPP calculations at my k2 princeton-personal site; also, all the `fpp.ini` files that control the calculations are in the `fpp/fppmodels` directory of the repo on github, so those should be able to be run by anyone who downloads the code.

Vespa documentation is up at http://vespa.readthedocs.org.
