### ISSUE TITLE
Stellar Parameters

### ISSUE THREAD

**Issue by benmontet** [benmontet/k2-characterization#2]
@dfm 

We have two estimates of the stellar parameters from photometry (using two different stellar evolution models).

There is statistical noise (from the photometry) leading to uncertainties in the physical parameters.

Each model also comes with its own (unknown) systematic noise.

Any thoughts on the best way to combine these into one posterior that includes the statistical noise and some honest assessment of the level of systematics influencing our values?

See the figure in this repository from group meeting today for a picture of what our stellar properties look like in the two models for clarity.

**Comment by timothydmorton** [comment]
Everything I've heard leans to community consensus being that Dartmouth models are better than the Padova ones.  So I'd lean towards relying on those rather than trying to average b/w models or something of that ilk.

I've put up an example of applying my [isochrones](https://github.com/timothydmorton/isochrones/) package to an example star (EPIC 201208431), and it returns what looks like are more-or-less reasonable posteriors, as shown in [this notebook](http://nbviewer.ipython.org/github/benmontet/k2-characterization/blob/fpp/fpp/starmodels.ipynb), with Teff histogram below.  Caveat here is that I'm not utilizing the WISE magnitudes, because the Dartmouth grids I downloaded awhile ago didn't have them.

I'm happy to set this up to generate such chains for all our candidates if you guys think that would be valuable.

![image](https://cloud.githubusercontent.com/assets/1895387/6343162/88715594-bbb1-11e4-8851-d078e9e9383f.png)

**Comment by timothydmorton** [comment]
Also, I should note that I require an upper limit for A_V extinction, which I sort of arbitrarily placed at 0.4, which may be high; I'm not really sure?

**Comment by benmontet** [comment]
Hi Tim,

This is interesting and great. I'm more than happy to use these!

Presumably the A_V extinction should be very low---we're looking straight
out of the galactic plane. I don't know what a reasonable upper limit is
though.

I see your peak in the posterior is aligned with mine, but yours is broader
(and probably more representative of the Truth from the photometry). Are
you treating photometric/model uncertainties in some creative way? Or do
you think this is just caused by marginalizing over extinction (which I'm
not doing at all).

Finally, I see there is a file in your repository called padova.py. I would
be interested to see your comparison with the padova grids, especially
given Ellie Newton et al.'s paper (2015) on the possibility that Dartmouth
underestimates K/M radii by ~15%, which aligns with the section of Jon
Swift's paper that was ultimately cut out (and my LHS 6343 paper, although
that is only one data point).

Best,
Ben

**Comment by timothydmorton** [comment]
The only "creative" thing I think I'm doing is using a 3D linear interpolation in (mass, age, feh) to predict observable quantities (e.g., the magnitudes).  Other than that, I'm just defining a chi-sq likelihood and sampling.

I tried running the Padova fit just now, but I killed it b/c it was taking too long, which isn't a great sign (the Dartmouth fit takes only maybe 15-30s), so not sure what's going on there...  I'll drop it in here if I get it. 

Also, I think I'll use this opportunity to modernize my Dartmouth models (e.g. include WISE, etc.).  I don't think anyone would raise a fit if we just stuck with Dartmouth.

**Comment by timothydmorton** [comment]
n.b. marginalizing over extinction does seem to make most of the difference, it appears; the notebook now has maxAV=0.1, and gives a Teff posterior like this:

![image](https://cloud.githubusercontent.com/assets/1895387/6343693/3e6be388-bbbb-11e4-9d58-4563d4a88ef6.png)

There does seem to be discrepancy with our mass estimates though, even though our temperatures are pretty close--- you get ~0.6 Msun, and I get:

![image](https://cloud.githubusercontent.com/assets/1895387/6343705/6e259ee8-bbbb-11e4-810b-fc244e1e86e9.png)

Will revisit when I have the new Dartmouth grids running...might be a couple days; we'll see.  For now I'll just take your parameters as given; they don't matter all that much for FPP anyway.

**Comment by benmontet** [comment]
Looks like that's entirely driven by the WISE data: when I eliminate that
from my likelihood function I get logg of 4.77 \pm 0.08, mass of 0.050 \pm
0.05, and a distance of 166 \pm 32 pc.

Have models for the WISE data ever been tested? It seems to be they should
just work since you're way over on the tail of the Planck distribution, but
I suppose there's probably a lot of molecular opacity issues that are
uncertain.

**Comment by benmontet** [comment]
Inspired by this conversation, I compared my fits to the photometry both including and excluding the WISE data:

![20150224_dartmouthcompare](https://cloud.githubusercontent.com/assets/1314530/6359052/127f0d44-bc3e-11e4-801e-40129f2c2806.png)

Things appear to be systematically different in the low-mass end! In the same direction with Ellie's paper and Jon's finding, that the current standard practices with the Dartmouth models give you radii that are too small.

We only have one spectroscopic data point to compare against, but 201912552 I find a radius that is too small with BVgriJHK, but one that is bang on Andrew Mann's SPEX value when I include WISE.

Conclusion: I think we should definitely include the WISE data, and I will make this very clear in the text.

**Comment by timothydmorton** [comment]
Nice!  Even more motivation for me to update my Dartmouth grids.

What are the sources of the photometry?  Is it possible that the sources for the BVgri photometry are just less reliable than 2MASS and WISE?

**Comment by benmontet** [comment]
It's plausible. They're all from APASS DR6, as recorded in UCAC4. I don't
have a definitive answer for you, except that I will point you to Thompson+
2014 (http://arxiv.org/abs/1408.1684) who claim the Dartmouth models are
too blue in near-IR colors because of their reliance on BT-Settl. I could
imagine how that could bias you to low masses, but have no proof that this
is actually the case.

**Comment by timothydmorton** [comment]
Moving stellar parameter discussion back here from the FPP thread...so I downloaded the new Dartmouth tracks including WISE filters from the DSEP page; the only reason I haven't incorporated these directly is that I'd like a bit better Fe/H sampling than by default comes with their .tgz packaged isochrone files (tracks separated by 0.5 dex, generally).  You can download files for interpolated Fe/H's from their web form, but then you have to do it manually, and rename the files all correctly (so that my code can parse), and they only go down to 1Gyr...None of these are serious problems, but it's why I've stalled on the upgrade.

Actually, I realized I should just test what I have before caring about better metallicity grids, but then I ran into the issue that I need A([band])/A(V) for all the bands that we care about.  @benmontet, if you could figure these out for me, that would be a big help.  The table that I'm currently reading from to calculate exctinction is [here](https://github.com/timothydmorton/isochrones/blob/master/isochrones/data/extinction.txt) (colums for R=3.1 and R=5 laws, I think, but I usually only use 3.1); if you can do some detective work and find what these numbers should be for all the rest of the bands for which you are quoting magnitudes (I think maybe W1-W4 are the only ones that I'm missing), then I can drop those in and run these through relatively quickly using just the sparsely sampled Fe/H grids that I have now.

**Comment by benmontet** [comment]
I'm on it!

**Comment by benmontet** [comment]
Okay, I submitted a pull request. (And gave a description of what I did over there)

**Comment by timothydmorton** [comment]
Great!  I get basically identical results to yours now

![image](https://cloud.githubusercontent.com/assets/1895387/6402007/4f9960ea-bdd2-11e4-9cba-c51b1ec0b451.png)

So I'm not sure we gain a whole lot by including extinction.  And just for kicks, if you drop everything but JHK + WISE, you get the following, which have somewhat more sensible error bars....

![image](https://cloud.githubusercontent.com/assets/1895387/6402075/de0bdf06-bdd2-11e4-9997-537d6492233a.png)

![image](https://cloud.githubusercontent.com/assets/1895387/6402080/e37fd60e-bdd2-11e4-8109-803025e1f82c.png)

**Comment by benmontet** [comment]
Okay great!

I agree with your assessment that JHK+WISE gives more believable error
bars. And if we only use those then extinction should definitely be
negligible, especially since we're only looking ~200 pc away and almost
straight out of the galaxy.

I'll defer to your judgement on what bands to include.

Am I correct that you will return a grid of [Teff, Mass, Logg, Distance,
Weight, Likelihood], or something equivalent?

**Comment by timothydmorton** [comment]
I think for now, let's stick with JHK+WISE for all the above reasons?  That's what I'd lean towards.... though we can also include the results for everything also, just to be complete.... and just for 

I sample in the mass-age-feh-distance-AV space, so I get a grid of samples of those parameters, but then that can be converted to samples of [insert derived property here] by evaluating the Dartmouth models at the sample locations.

**Comment by benmontet** [comment]
Sounds great.

Those definitely seem like the most proper things to sample in given the
way the Dartmouth models are set up. If you can also produce samples in
Teff and something that can easily be turned into mass (mass, logg, or
stellar density) that would be fantastic---and it looks like you're already
set up for that based on the plots you've been making?

**Comment by timothydmorton** [comment]
I've posted samples for all my isochrone fits [here](http://www.astro.princeton.edu/~tdm/k2/starmodels/).  Each .h5 file has a `samples` table with tons of columns corresponding to evaluating the isochrones at the sample locations.  Included are `mass`, `radius`, `Teff`, `logg`, etc.  I haven't summarized them or made triangle plots or anything yet, but it's all there for the taking.

**Comment by benmontet** [comment]
My hero! Excellent.

**Comment by benmontet** [comment]
I'm trying to plot these (see 'stellarprops.py' in the main repository) and I'm seeing some strange things. Specifically, 201912552 (the mid M that we have a spectrum for) is giving some very hot results, which I don't see in mine---I'm consistent with Mann.

I'm also getting something strange going on with 201855371.

Can you verify my understanding that you're using JHK + W1-W3, and that I'm not doing anything blatantly wrong in my reading in of your files?

**Comment by timothydmorton** [comment]
ok, weird.  It looks like for some reason the _max_ age being allowed is 1 Gyr, which is throwing things off.  This must be a bug with me migrating to the newer grids.  Looking into it.

**Comment by timothydmorton** [comment]
OK, that theory doesn't seem to be right...it just seems to be not working well for that one; I don't yet see why.

I am using just JHK+W1-3....do other stars match what you got or am I all over the map?

**Comment by benmontet** [comment]
The very last two (201912552 and 201929294) are both pretty discrepant from what I see, but everything else that's not obviously broken is more or less aligned with my expectations.

There are ~10 though where the sampler doesn't seem to step around---all the samples are at the same place. 201569483 and 201367065 are examples of this.

**Comment by dfm** [comment]
Any thoughts on why the mass and radius for 201367065 are inconsistent at >2-sigma with the spectroscopic numbers from Crossfield et al.? Are these just those systematic uncertainties that y'all were talking about?

**Comment by timothydmorton** [comment]
One reason could be that this one is a good example where the different photometric bands are pulling in different directions--- that is, the models do not explain it particularly well.  The ["observed" triangle plot](http://www.astro.princeton.edu/~tdm/k2/starmodels/201367065_observed.png) demonstrates this: B, V, i, and W3 are off the 99% extent.

I think I'll also do a run using just JHK+WISE; no reason not to.

**Comment by timothydmorton** [comment]
hmm... JHK+WISE doesn't seem to bring it any closer:

http://www.astro.princeton.edu/~tdm/k2/starmodels_JHKWISE/201367065_physical.png
http://www.astro.princeton.edu/~tdm/k2/starmodels_JHKWISE/201367065_observed.png

I should run a model using their spectroscopic params to see what I get.  0.6 Msun seems a bit big to me for 3900 K?  Adding this to the queue.

**Comment by benmontet** [comment]
To add to the confusion, Kevin Apps emailed us about this one a while back,
and with his photometric estimates thought Crossfield+ missed the other
way. He pegged it as a metal rich (+0.2 dex) late K (0.68 \pm 0.05 Msun)
dwarf at 54 \pm 5 pc.

Ahh, systematics.

**Comment by timothydmorton** [comment]
Sampling the Dartmouth models with the Teff and Fe/H from Crossfield et al. gives the following, significantly inconsistent with their quoted values.  

![index](https://cloud.githubusercontent.com/assets/1895387/6488018/b09ae942-c262-11e4-93ec-ef979a201f5b.png)

**Comment by benmontet** [comment]
That's really interesting. I wonder if we can chalk this up to "Dartmouth
models underpredict radii of M0-M1 dwarfs" or if there's something else
going on.

**Comment by dfm** [comment]
Damn. Well this is why I try to avoid doing "astronomy". I think that I'm all set up to run on whatever distributions we decide on. Sorry for being slow; I'm in Germany getting overwhelmed by people who study "causal inference"... I still don't even know what that means but it's probably relevant...

**Comment by benmontet** [comment]
We've put it off, but it's probably time to have this discussion. I see a few options on how to treat the stellar parameters

1) We could give star + planet properties assuming the MCMC errors are "correct" and ignore the systematics. We then will say in the text that these parameters are model dependent and could have ~10-15 percent biases.

2) We could in some way inflate the uncertainties by adding random noise somewhere to get accurate error bars that we believe reflect the true uncertainties. We then will say that we do this and that our level of noise isn't really statistically motivated, but empirically accurate (and the biases haven't been corrected, if they exist).

3) We could accomplish the same effect by changing our acceptance fraction, effectively inflating our uncertainties in the photometry. This is perhaps even less physically motivated, because we believe our photometry is pretty good, but would have the same effect as (2). 

3a) Likewise, we could use fewer bandpasses to have a less well-constrained fit.

Do either of you have any thoughts? I think various readers will complain about any of these decisions. Perhaps (1) would be the most offensive to people, but not necessarily the people we're worried about offending? I'm comfortable with any of these decisions, as long as we clearly explain what we did and defend why we did it.

**Comment by dfm** [comment]
I have opinions about really extreme things that be done at earlier stages in the fitting but it's probably not the time to go into them. I'd be happy to do something like 2 and it would even be possible to report both 1 and 2. I don't really understand what you mean by 3 at all...

Another relevant point is that I'm actually using the MCMC chains that I ran for Paper 1 so if other people come up with their own stellar parameters, it would be easy for them to test what that means for the planet parameters under the likelihood function that we used...

**Comment by timothydmorton** [comment]
I'm happy to do option 2; I like the idea of doing both 1 and 2 and reporting them both.  I could just inflate all the uncertainties on the photometry by a factor of 3 and re-run.

**Comment by benmontet** [comment]
Okay let's do 1 and 2. I agree that reporting multiple would be the best
thing.

Dan, will you mention that in your section? That if someone has their own
parameters they can rerun with your publicly available chains and be in
business?

I would also be interested to hear your thoughts on the "really extreme
things" sometime. Maybe over a beer once we're all submitted.

**Comment by timothydmorton** [comment]
I've put up Option 2 fits at http://www.astro.princeton.edu/~tdm/k2/starmodels_inflated/

**Comment by benmontet** [comment]
Okay, these look really great to me. These definitely look like uncertainties at the level which I believe them (perhaps with systematic offsets because of the models) from photometry. I'm totally on board with two tables, one with these and one with the others, which I'll make.
