### ISSUE TITLE
add detected signal depth (ppt) to detected companion table

### ISSUE THREAD

**Issue by timothydmorton** [benmontet/k2-characterization#20]
so as to be able to compare immediately w/ "Max Depth"

**Comment by benmontet** [comment]
Good idea. I'll add this in.

**Comment by benmontet** [comment]
@dfm you might be more set up to do this quickly than I am. Would you be interested in adding this (or supplying a column which I'll add in) while I address Hogg's comments?

**Comment by timothydmorton** [comment]
`paper1_tab-cand.tex` is in the `fpp` folder.

**Comment by timothydmorton** [comment]
ah, but that doesn't have depth explicitly...never mind

**Comment by timothydmorton** [comment]
ok, i just added a file called `depths_ppt.txt` with `candidate depth[ppt]`

**Comment by timothydmorton** [comment]
that is, `depth = rprs**2 * 1000`, with rprs taken from the paper 1 table.

**Comment by benmontet** [comment]
Okay. I don't know where Dan's chains are, which is presumably the ideal way to get the correct values/uncertainties. I'll drop these in now and @dfm please point me to your samples/update this.

**Comment by benmontet** [comment]
Updated (for now)

**Comment by dfm** [comment]
I've updated depths_ppt.txt using the radius ratios based on my final samplings. This depth is screwed up for the grazing transit (201257461) but otherwise there's not much of a change.

**Comment by benmontet** [comment]
I've updated that table.
