### ISSUE TITLE
Final comments.

### ISSUE THREAD

**Issue by timothydmorton** [benmontet/k2-characterization#22]
Just opening a general issue here; I believe I have finished my contributions to the text.  In addition to the FPP table, these are mainly in Section 4, where I've done some re-organizing, a paragraph in the conclusion, and small edits to the abstract.  If there's any chance we could submit before the deadline today (i.e. in the next 90 minutes), that would be fantastic; that way I could present at coffee tomorrow at Princeton before leaving for a week.  If not, no worries, then I'll talk about it at Caltech on Monday!

**Comment by benmontet** [comment]
I'm still writing systematics. 

One or more of us needs to go through and make sure all the FPP numbers throughout are correct. Nvalidated, Nfp and Nlimbo aren't always used in the text---sometimes they're just numbers, and I'm sure those are wrong somewhere.

There's a chance on 4pm, but I'd peg it at no better than 50/50. Worst case I think we can submit to ApJ tonight and to the arXiv on Friday afternoon.

**Comment by benmontet** [comment]
Okay, systematics words done. @dfm plz read through them and change anything you disagree with.

**Comment by dfm** [comment]
Reading now.

**Comment by benmontet** [comment]
We need the following:

1) Hogg wants more words about FPs in the intro, fewer words about K2 search and detrending.

2) I need to update figure 2 with the right FP/planet/candidate labels.

3) We need to make sure the numbers are consistent and correct throughout.

4) I want to add a column into planet properties table that gives planet/candidate/FP status.

5) Submit to arXiv.

I am going to do these in the order 2, 4, 3, 1, 5. Anyone else can jump in on any of these (except 5)

**Comment by benmontet** [comment]
Done with 2 and 4. Will hack up 1 next, then 3.

**Comment by dfm** [comment]
I'm working on 3 now.

**Comment by timothydmorton** [comment]
Sorry I'm away from computer now, otherwise I'd take care of 1... If we
don't make 4pm I can do that later tonight

**Comment by benmontet** [comment]
I put a couple words; if we don't make 4pm you are of course welcome to add in more.

**Comment by benmontet** [comment]
I sign off on the paper. Tim did as well, @dfm do you?

**Comment by dfm** [comment]
Yup. Looks great! Well done y'all!

**Comment by benmontet** [comment]
Okay, we are ready to post right at 4. You have six minutes to change your minds.

**Comment by dfm** [comment]
:beers:

**Comment by benmontet** [comment]
Colloquium here starts at 4, and I want to go to it (Gaia) so I'll submit to ApJ/email out to everyone tonight.

**Comment by timothydmorton** [comment]
Before 4 so as to get in on Friday?

**Comment by benmontet** [comment]
At 4 to be top of the Sunday night mailing. In time for your travels, and you can talk about it at Princeton any time you want!

**Comment by timothydmorton** [comment]
Alright good call! Awesome work guys.

**Comment by benmontet** [comment]
Yes, nice job everyone!
