### ISSUE TITLE
New stellar parameter fits and FPP calculations

### ISSUE THREAD

**Issue by timothydmorton** [benmontet/k2-characterization#23]
I've now run new StarModel fits (using MultiNest rather than emcee), and the corresponding new FPP calculations.  The new fit results (still based on the 3x inflated photometric errors) are up at www.astro.princeton.edu/~tdm/k2/starmodels.  

I'm not sure the best way to communicate these results, as some of the fits (like [201384232](http://www.astro.princeton.edu/~tdm/k2/starmodels/201384232_physical.png)) are multi-modal.  @benmontet, take a look at these and think it over.  One thing I found interesting was that [201257461](http://www.astro.princeton.edu/~tdm/k2/starmodels/201257461_physical.png) and [201929294](http://www.astro.princeton.edu/~tdm/k2/starmodels/201929294_physical.png), that Dan Huber said were giants, actually now both look like giants from the photometry.

The FPP results change only slightly, but a couple things shuffle between planet/candidate status.  Fortunately, I don't think anything went from being a planet to being a FP, which is good.  Sometime relatively soon I hope to get around to updating the paper text.  Please poke me if you want me to do it quicker.

**Comment by timothydmorton** [comment]
OK, now the new (I believe, final) StarModel fits are now up at www.astro.princeton.edu/~tdm/k2/starmodels.  Also the recalculated FPP table is now in the document.  By my count we now have 19 planets; there's some minor shuffling at the 1% boundary.

**Comment by benmontet** [comment]
Great!
