### ISSUE TITLE
Planet parameters

### ISSUE THREAD

**Issue by dfm** [benmontet/k2-characterization#3]
I've added a notebook where I use the values from `dartmouth_params.txt` and my MCMC samples from Paper 1 to measure the properties of the 2 planets from Crossfield et al. It looks like I'll need to take longer chains in order to fully sample the distribution but it doesn't look too bad so far. The results are more or less consistent with what they get even though the stellar parameters in our table are somewhat different than their spectral results.

I'll add some text to the document next.

Link: http://nbviewer.ipython.org/github/benmontet/k2-characterization/blob/master/planet_properties.ipynb

**Comment by benmontet** [comment]
Okay that sounds great to me! Looking forward to seeing what they all look
like once we are ready to run with stellar properties.

**Comment by benmontet** [comment]
The table titled "Planet Properties for all Objects of Interest" doesn't have all objects of interest in it. It appears to have 32/36 planets.

**Comment by benmontet** [comment]
(Also I changed the format very slightly)
