### ISSUE TITLE
trapezoid sample files?

### ISSUE THREAD

**Issue by timothydmorton** [benmontet/k2-characterization#4]
Hey @dfm-- for some reason I can't open your .h5 files using pandas, and they show up empty...any idea why?  See [here](http://nbviewer.ipython.org/github/benmontet/k2-characterization/blob/fpp/fpp/test.ipynb).

**Comment by timothydmorton** [comment]
I can open it fine with h5py; it'd be nice to know why pandas is breaking, though.

**Comment by dfm** [comment]
I didn't save it using pandas so it doesn't have the right format. Here's how I would get it into a DataFrame:

```
import h5py
import numpy as np
import pandas as pd

with h5py.File("201208431.h5", "r") as f:
    samples = f["samples"][...]

cols = ["T", "delta", "T_tau", "period", "t0"]
df = pd.DataFrame.from_items(zip(cols, samples[:, :5].T))
```

**Comment by dfm** [comment]
Then for each candidate in the multis, you could do something like:

```
for i in range(0, samples.shape[1], 5):
    df = pd.DataFrame.from_items(zip(cols, samples[:, i:i+5].T))
```

**Comment by timothydmorton** [comment]
thanks!
