### ISSUE TITLE
201912552 stellar params, etc.

### ISSUE THREAD

**Issue by timothydmorton** [benmontet/k2-characterization#6]
@benmontet - I'm focusing on 201912552 to try to understand what's up with my stellar isochrones code.  My MCMC stubbornly wants to give it a ~9000K temperature, which we know is absurd.  

I'll be working on this by putting together some diagnostic plots showing samples & evolution tracks, but this will take some setup; in the meantime, any thoughts you have on this would be welcome.

**Comment by benmontet** [comment]
Good, I like this plan.

I will think about this specific one more too. How are you initializing
your MCMC?

I can't imagine that there's some weird line blanketing thing going on that
makes a mid-M look like an A star in JHKW1-3 color space, can you? I'll
look at the models closely and try to see if the results you're getting are
in some sense physical.

**Comment by timothydmorton** [comment]
See `fit_mcmc` over [here](https://github.com/timothydmorton/isochrones/blob/new-dartmouth/isochrones/starmodel.py): 

I've tried with `initial_burn` both off and on.  Also tried with just JHK and with just WISE.

**Comment by benmontet** [comment]
The star it's trying to fit is a very low-metallicity star, which isn't a
truly terrible fit, but it's not very good relative to what we know the
true answer to be. I wonder if somehow your initial fit isn't probing the
range of parameters that correspond to the true values, so it's finding
this mediocre fit and never steps into the mid-M parameter space?

That doesn't explain why the M4 star 201465501 is well fit by your system
though.

**Comment by timothydmorton** [comment]
So, I found a couple things-- one, I had a bug in my `initial_burn` option--- I wasn't re-randomizing the walkers at the end of the initial burn.  Also, I added an option to enforce a max distance, which is a bit of a hack, but does seem to nudge things in the right direction:

![triangle](https://cloud.githubusercontent.com/assets/1895387/6467702/e97a3b52-c19d-11e4-808c-7d2b741738f0.png)

There's still a bit of straggling going on into larger masses, but this at least calms the insanity.

**Comment by timothydmorton** [comment]
I think what might have been going on is that in my initial walker randomization, I am randomizing the distances ~d^2, and for a close distance like this, probably no walkers are landing anywhere close to the right distance.  I'll tune this some more to try to avoid this behavior.

**Comment by benmontet** [comment]
That sounds reasonable to me. I think that's probably the explanation,
given that it's finding a somewhat okay fit in a region of space really far
away from the truth (and at a large distance).

Re-randomizing the walkers is probably also what was causing the issue
where some of the stars never had walkers move away from their initial
guess, no?

**Comment by timothydmorton** [comment]
Yup!  I'm futzing around a bit more and then I'll re-run them all.

**Comment by timothydmorton** [comment]
just for kicks, I added back in BVgri and re-fit with these bug-fixes in place.... how does this compare to the spectroscopic params (in particular, feh)? 

![triangle](https://cloud.githubusercontent.com/assets/1895387/6468408/ca79a120-c1a2-11e4-855f-04cbf7aebea0.png)

Just JHK+WISE prefers a more metal-poor, warmer star (more like ~4000 K).

**Comment by benmontet** [comment]
They are well in agreement! The spectroscopic params are:

SpT = M2.8
Teff = 3503 +/- 60 K
[Fe/H] = 0.09 +/- 0.09
R\* = 0.394 +/- 0.038 R_sun
Mass = 0.413 +/- 0.043 M_sun

**Comment by timothydmorton** [comment]
Fantastic.  I'm going to put back in all the bands (except W4) and re-run everything, and not apologize for small error bars!

**Comment by benmontet** [comment]
Great! I will add text to remind the dear reader about the difference
between statistical and systematic errors.
