### ISSUE TITLE
Binary stars?

### ISSUE THREAD

**Issue by timothydmorton** [benmontet/k2-characterization#7]
I wonder whether any of the stars that show signs of bi-modality in the MCMC photometry fits are actually binaries... cross-check the following with the AO observations:

201367065
201393098
201445392 (not clear bi-modality, but funky-looking)
201546283
201569483
201596316
201855371 (*if this is a binary, I love it.)
201929294 (ditto)

**Comment by benmontet** [comment]
Of these--- 201367065 is clear. This is the Crossfield+ system, and they have AO. 201929294 is the giant according to Huber (via reduced PM), 201546283 is a binary from Bowler, and the rest we don't have AO data for.
