### ISSUE TITLE
Giants?

### ISSUE THREAD

**Issue by benmontet** [benmontet/k2-characterization#8]
Dan Huber claims 201257461 and 201929294 are giants. The former has a logg from RAVE which is consistent with a halo giant, while the latter comes from reduced proper motion. 

This might explain some of the weirdness in the fit for 201929294. @timothydmorton, what's the upper mass limit in the Dartmouth isochrones as you use them? It looks like the default is only a couple solar masses, so if these are giants, they might just not be in the parameter space covered by Dartmouth models.

**Comment by timothydmorton** [comment]
I'm not using an upper mass limit, but I imposed an upper distance limit of 500pc, which would likely exclude giant solutions...the Dartmouth grids as I'm using them extend to ~3.7 Msun.

**Comment by benmontet** [comment]
Okay. I will note this in the text.
